"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import type { SceneProps } from "./kit";

/** One drawing per declared visual id. Each loads with the article that uses it. */
export const SCENES: Record<string, ComponentType<SceneProps>> = {
  "text-becomes-integers": dynamic(() => import("./text-becomes-integers")),
  "one-step-of-generation": dynamic(() => import("./one-step-of-generation")),
  "six-stages-to-a-grounded-answer": dynamic(() => import("./six-stages-to-a-grounded-answer")),
  "instruction-and-contract": dynamic(() => import("./instruction-and-contract")),
  "governed-execution-pipeline": dynamic(() => import("./governed-execution-pipeline")),
  "present-approval-judgment": dynamic(() => import("./present-approval-judgment")),
  "what-each-check-establishes": dynamic(() => import("./what-each-check-establishes")),
  "what-crosses-the-handoff": dynamic(() => import("./what-crosses-the-handoff")),
  "ready-for-what": dynamic(() => import("./ready-for-what")),
  "runtime-choice-comparison": dynamic(() => import("./runtime-choice-comparison")),
  "tool-use-loop": dynamic(() => import("./tool-use-loop")),
  "what-writes-the-parameters": dynamic(() => import("./what-writes-the-parameters")),
  "local-success-is-not-system-success": dynamic(() => import("./local-success-is-not-system-success")),
  "requested-done-worked": dynamic(() => import("./requested-done-worked")),
  "what-is-in-the-window": dynamic(() => import("./what-is-in-the-window")),
  "a-phrase-or-a-package": dynamic(() => import("./a-phrase-or-a-package")),
  "the-five-minute-version": dynamic(() => import("./the-five-minute-version")),
  "three-questions-for-a-record": dynamic(() => import("./three-questions-for-a-record")),
  "three-things-not-one": dynamic(() => import("./three-things-not-one")),
  "a-mood-or-a-step": dynamic(() => import("./a-mood-or-a-step")),
  "close-in-wording-opposite-in-answer": dynamic(() => import("./close-in-wording-opposite-in-answer")),
  "what-a-publisher-holds": dynamic(() => import("./what-a-publisher-holds")),
  "four-questions-five-words": dynamic(() => import("./four-questions-five-words")),
  "five-checks-each-establishing-less": dynamic(() => import("./five-checks-each-establishing-less")),
  "three-quiet-degradations": dynamic(() => import("./three-quiet-degradations")),
  "six-fields-of-an-instruction-spec": dynamic(() => import("./six-fields-of-an-instruction-spec")),
  "resident-or-invoked": dynamic(() => import("./resident-or-invoked")),
  "the-pipeline-runs-one-way": dynamic(() => import("./the-pipeline-runs-one-way")),
  "a-decision-made-three-times": dynamic(() => import("./a-decision-made-three-times")),
  "instruction-or-state": dynamic(() => import("./instruction-or-state")),
  "what-makes-it-a-handoff": dynamic(() => import("./what-makes-it-a-handoff")),
  "payload-or-shared-store": dynamic(() => import("./payload-or-shared-store")),
  "a-file-called-current": dynamic(() => import("./a-file-called-current")),
  "when-the-next-step-cannot-proceed": dynamic(() => import("./when-the-next-step-cannot-proceed")),
  "replay-or-resume": dynamic(() => import("./replay-or-resume")),
  "five-words-for-ready": dynamic(() => import("./five-words-for-ready")),
  "demo-or-readiness": dynamic(() => import("./demo-or-readiness")),
  "adjacent-is-not-evidence": dynamic(() => import("./adjacent-is-not-evidence")),
  "criterion-before-or-after": dynamic(() => import("./criterion-before-or-after")),
  "what-the-gates-establish": dynamic(() => import("./what-the-gates-establish")),
  "safe-ways-to-stop": dynamic(() => import("./safe-ways-to-stop")),
  "what-can-be-undone": dynamic(() => import("./what-can-be-undone")),
  "the-decision-expires": dynamic(() => import("./the-decision-expires")),
  "is-it-still-open": dynamic(() => import("./is-it-still-open")),
  "which-human": dynamic(() => import("./which-human")),
  "what-no-does": dynamic(() => import("./what-no-does")),
  "what-the-merge-reserves": dynamic(() => import("./what-the-merge-reserves")),
  "rank-four-of-three": dynamic(() => import("./rank-four-of-three")),
  "lexical-or-vector": dynamic(() => import("./lexical-or-vector")),
  "close-and-outdated": dynamic(() => import("./close-and-outdated")),
  "where-it-was-lost": dynamic(() => import("./where-it-was-lost")),
  "permission-is-its-own-question": dynamic(() => import("./permission-is-its-own-question")),
  "what-kind-of-unsure": dynamic(() => import("./what-kind-of-unsure")),
  "two-hundred-and-unchanged": dynamic(() => import("./two-hundred-and-unchanged")),
  "lookup-or-continuation": dynamic(() => import("./lookup-or-continuation")),
  "likely-confident-true": dynamic(() => import("./likely-confident-true")),
  "model-or-application": dynamic(() => import("./model-or-application")),
  "property-not-quality": dynamic(() => import("./property-not-quality")),
  "the-fixed-set": dynamic(() => import("./the-fixed-set")),
  "close-the-loop": dynamic(() => import("./close-the-loop")),
  "narrow-not-closed": dynamic(() => import("./narrow-not-closed")),
  "read-the-gap": dynamic(() => import("./read-the-gap")),
  "prompt-like-code": dynamic(() => import("./prompt-like-code")),
  "where-content-crosses-in": dynamic(() => import("./where-content-crosses-in")),
  "quality-or-security": dynamic(() => import("./quality-or-security")),
  "where-the-rule-lives": dynamic(() => import("./where-the-rule-lives")),
  "what-isolation-bounds": dynamic(() => import("./what-isolation-bounds")),
  "the-way-back": dynamic(() => import("./the-way-back")),
  "prose-or-surface": dynamic(() => import("./prose-or-surface")),
  "the-label-is-a-view": dynamic(() => import("./the-label-is-a-view")),
  "a-button-is-a-request": dynamic(() => import("./a-button-is-a-request")),
  "the-slot-was-taken": dynamic(() => import("./the-slot-was-taken")),
  "interactive-not-acting": dynamic(() => import("./interactive-not-acting")),
  "what-the-surface-is-for": dynamic(() => import("./what-the-surface-is-for")),

  // Works On My Prompt sheets: the steps of a sheet, keyed by its `scene`.
  // Not article visuals, so they stay out of SCENE_IDS.
  "write-it-down-or-watch-it-guess": dynamic(() => import("./write-it-down-or-watch-it-guess")),
  "better-than-last-week-prove-it": dynamic(() => import("./better-than-last-week-prove-it")),
  "upload-everything-read-nothing": dynamic(() => import("./upload-everything-read-nothing")),
};
